### ISSUE TITLE
how to run this project?

### ISSUE THREAD

**Issue by TTTJJJWWW** [matln/voxceleb_triplet-loss#1]
Hi! @matln 
how to run this project?
can you give me a example? thanks!

**Comment by matln** [comment]
I have cleaned redundant code and updated `readme.md`. You may try to clone this repo and run `train.py` after changing your paths and GPU configuration in `constants.py`.

**Comment by TTTJJJWWW** [comment]
@matln 感谢帮助，我下载了voxceleb1的数据集，解压之后是否需要改变文件结构？就是运行您的代码要求dir路径下的文件结构是什么样的？

**Comment by matln** [comment]
voxceleb1_dir目录有`\voxceleb1_wav`和`voxceleb1_Verification.txt`等子目录。`voxceleb1_wav`下是1251个文件夹，对应1251个说话人，文件夹名是每个**说话人的姓名**。里面包含这个人所有的wav文件。`voxceleb1_Verification.txt`就是官方给出的测试计划。但是后来官方为了与voxceleb2统一，将1251个文件夹的名字变成了**说话人的ID**，包括测试计划也是，你下的数据集应该对应的文件夹名是说话人的ID。所以你可能需要重新运行`speaker_id.py`和`voxceleb1_veri_list.py`生成对应的txt文件，将`.txt`文件中说话人的姓名变成对应ID。

另外，代码中标有`:TODO`的地方要注意根据情况进行更改

**Comment by TTTJJJWWW** [comment]
@matln  感谢指点！大佬在做说话人相关的工程和研究吗？我正在做相关工作，如果可以我们可以邮件或微信交流吗？如果我能成功运行这个代码我也会在论文中引用这个project的。

**Comment by TTTJJJWWW** [comment]
@matln  也就是说根目录就填voxceleb的路径就行了？根目录下是`vox1_dev_txt.zip`，`vox1_dev_wav.zip`，`vox1_test_txt.zip`，`vox1_test_wav.zip`四个压缩包和`vox1_meta.csv`文件。解压之后合并成一个`wav`文件夹和一个`txt`文件夹，这样根目录下不用变了？直接在代码里设置好根目录并重新运行`speaker_id.py`和`voxceleb1_veri_list.py`生成对应的txt文件就可以了吗？

**Comment by matln** [comment]
好的没问题，邮件微信都可以随时交流！我刚刚看了一下，认为最好还是不要合并了，因为在代码中有一行是`speakers = list(filter(kambda x: x[:1] == 'E', speakers))`。因为现在wav文件夹的名字是每个说话人的ID，所以这行代码就失效了。

**Comment by matln** [comment]
如果合并的话，你可以根据`vox1_meta.csv`制作一个字典，将说话人ID与姓名对应起来，这样需要改的地方就很少了。

**Comment by TTTJJJWWW** [comment]
因为训练集和测试集压缩名都是WAV，如果不合并需要分别怎么命名呢？因为设置的path是到voxceleb文件夹的根目录吧？不重新做字典重新可以生成新的TXT文件吗？

**Comment by matln** [comment]
假设根目录是`/voxceleb1`，里面有两个子文件夹`vox1_dev_wav`和`vox1_test_wav`，`vox1_dev_wav`有1211个说话人，`vox1_test_wav`有40个说话人，另外还有测试计划，就是官网中`Metadata -> List of trial pairs for Verification`。我不知道`vox_test_txt`与`vox1_dev_test`是什么内容

然后在改`speaker_id.py`的时候你可以只生成`dev`中1211个人的label，因为训练时另外40个人用不到标签。如果你不知道怎么改，可以通过邮件私下给我你的微信，然后等你有空时详细的跟你说一下。

**Comment by TTTJJJWWW** [comment]
@matln  邮件给你发微信啦，麻烦加一下谢谢！
